/**
 * Sound roles, sources, and settings for the configurable sound engine.
 *
 * A **role** is *when* a sound plays (the four moments the timer needs to announce); a
 * **source** is *what* plays (a synthesized tone, a bundled asset, or a user upload). The
 * two are kept independent so any source can serve any role, which is exactly what
 * requirement 3.2 asks the settings view to present.
 *
 * The synthesized tones in `lib/audio.ts` remain the default *and* the fallback: every
 * role has a `SynthId` associated with it ({@link ROLE_SYNTH}), so a source that fails to
 * load or decode never leaves a boundary silent (requirements 3.1, 3.7).
 *
 * This module is intentionally free of browser APIs — it is pure data and pure functions,
 * so it is safe to import from server components and trivial to unit test.
 *
 * Requirements: 3.1, 3.6, 3.7, 3.11
 */

/** The four moments the timer announces (requirement 3.1). */
export type SoundRole = 'roundStart' | 'restStart' | 'warningTick' | 'finished'

/** Every role, in the order the settings view lists them. */
export const SOUND_ROLES: readonly SoundRole[] = [
  'roundStart',
  'restStart',
  'warningTick',
  'finished',
]

/** Human-readable role names for the settings view. */
export const SOUND_ROLE_LABELS: Record<SoundRole, string> = {
  roundStart: 'Round start',
  restStart: 'Rest start',
  warningTick: 'Final-seconds tick',
  finished: 'Workout finished',
}

/** Short explanation of when each role fires, shown under its selector. */
export const SOUND_ROLE_HINTS: Record<SoundRole, string> = {
  roundStart: 'Plays when a round begins.',
  restStart: 'Plays when a rest period begins.',
  warningTick: 'Plays once per second for the last 3 seconds of a round.',
  finished: 'Plays when the last round ends.',
}

/** The synthesized tones generated by `lib/audio.ts`. No files, no network. */
export type SynthId = 'bell' | 'buzzer' | 'tick' | 'airhorn' | 'beep'

/** Every synth tone, in display order. */
export const SYNTH_IDS: readonly SynthId[] = ['bell', 'buzzer', 'tick', 'airhorn', 'beep']

/** Human-readable synth names for the settings view. */
export const SYNTH_LABELS: Record<SynthId, string> = {
  bell: 'Bell (synth)',
  buzzer: 'Buzzer (synth)',
  tick: 'Tick (synth)',
  airhorn: 'Air horn (synth)',
  beep: 'Beep (synth)',
}

/**
 * Where a role's audio comes from.
 *
 * - `synth` — generated on the fly by the Web Audio API; always available.
 * - `builtin` — an asset shipped under `public/sounds/` (see `lib/audio/builtins.ts`).
 * - `custom` — a validated user upload held in IndexedDB (see `lib/audio/customStore.ts`).
 */
export type SoundSource =
  | { kind: 'synth'; synthId: SynthId }
  | { kind: 'builtin'; assetPath: string }
  | { kind: 'custom'; blobId: string }

/** The persisted sound configuration (requirement 3.6). */
export interface SoundSettings {
  muted: boolean
  /** Output gain, in the inclusive range `[0, 1]` (requirement 3.8). */
  volume: number
  assignments: Record<SoundRole, SoundSource>
}

/**
 * The synth tone associated with each role — the default assignment *and* the fallback
 * played when an assigned source fails to load or decode (requirement 3.7), or when a
 * custom upload backing a role is deleted (requirement 3.11).
 */
export const ROLE_SYNTH: Record<SoundRole, SynthId> = {
  roundStart: 'bell',
  restStart: 'buzzer',
  warningTick: 'tick',
  finished: 'airhorn',
}

/** The default volume: loud enough to hear over a heavy bag, short of clipping. */
export const DEFAULT_VOLUME = 0.8

/** Restricts a volume to `[0, 1]`, mapping non-finite input to {@link DEFAULT_VOLUME}. */
export function clampVolume(value: unknown): number {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return DEFAULT_VOLUME
  return Math.min(1, Math.max(0, numeric))
}

/** The synth source for a role, i.e. its factory default and its fallback. */
export function synthSourceFor(role: SoundRole): SoundSource {
  return { kind: 'synth', synthId: ROLE_SYNTH[role] }
}

/** A fresh settings object: unmuted, default volume, every role on its synth tone. */
export function defaultSoundSettings(): SoundSettings {
  return {
    muted: false,
    volume: DEFAULT_VOLUME,
    assignments: {
      roundStart: synthSourceFor('roundStart'),
      restStart: synthSourceFor('restStart'),
      warningTick: synthSourceFor('warningTick'),
      finished: synthSourceFor('finished'),
    },
  }
}

/** `true` when two sources address the same audio. */
export function sameSoundSource(a: SoundSource, b: SoundSource): boolean {
  return encodeSoundSource(a) === encodeSoundSource(b)
}

/**
 * Stable string form of a source, used as the value of the settings `<Select>` and as the
 * cache key for decoded buffers.
 */
export function encodeSoundSource(source: SoundSource): string {
  switch (source.kind) {
    case 'synth':
      return `synth:${source.synthId}`
    case 'builtin':
      return `builtin:${source.assetPath}`
    default:
      return `custom:${source.blobId}`
  }
}

/** Parses {@link encodeSoundSource} output. Returns `null` for anything unrecognized. */
export function decodeSoundSource(value: unknown): SoundSource | null {
  if (typeof value !== 'string') return null
  const separator = value.indexOf(':')
  if (separator <= 0) return null

  const kind = value.slice(0, separator)
  const rest = value.slice(separator + 1)
  if (rest.length === 0) return null

  if (kind === 'synth') {
    return (SYNTH_IDS as readonly string[]).includes(rest)
      ? { kind: 'synth', synthId: rest as SynthId }
      : null
  }
  if (kind === 'builtin') return { kind: 'builtin', assetPath: rest }
  if (kind === 'custom') return { kind: 'custom', blobId: rest }
  return null
}

/** Coerces one stored assignment into a source, falling back to the role's synth tone. */
function normalizeSource(raw: unknown, role: SoundRole): SoundSource {
  if (typeof raw === 'string') return decodeSoundSource(raw) ?? synthSourceFor(role)

  const candidate = raw as Partial<Extract<SoundSource, { kind: string }>> | null | undefined
  if (!candidate || typeof candidate !== 'object') return synthSourceFor(role)

  if (candidate.kind === 'synth') {
    const synthId = (candidate as { synthId?: unknown }).synthId
    return (SYNTH_IDS as readonly string[]).includes(String(synthId))
      ? { kind: 'synth', synthId: synthId as SynthId }
      : synthSourceFor(role)
  }
  if (candidate.kind === 'builtin') {
    const assetPath = (candidate as { assetPath?: unknown }).assetPath
    return typeof assetPath === 'string' && assetPath.length > 0
      ? { kind: 'builtin', assetPath }
      : synthSourceFor(role)
  }
  if (candidate.kind === 'custom') {
    const blobId = (candidate as { blobId?: unknown }).blobId
    return typeof blobId === 'string' && blobId.length > 0
      ? { kind: 'custom', blobId }
      : synthSourceFor(role)
  }
  return synthSourceFor(role)
}

/**
 * Coerces arbitrary persisted JSON into well-formed {@link SoundSettings}.
 *
 * Nothing here throws: a corrupt or partial record degrades field by field to the
 * defaults, which is what makes reload restoration safe across app versions
 * (requirement 3.6).
 */
export function normalizeSoundSettings(raw: unknown): SoundSettings {
  const defaults = defaultSoundSettings()
  if (!raw || typeof raw !== 'object') return defaults

  const record = raw as { muted?: unknown; volume?: unknown; assignments?: unknown }
  const assignments = (record.assignments ?? {}) as Record<string, unknown>

  return {
    muted: record.muted === true,
    volume: clampVolume(record.volume ?? defaults.volume),
    assignments: {
      roundStart: normalizeSource(assignments.roundStart, 'roundStart'),
      restStart: normalizeSource(assignments.restStart, 'restStart'),
      warningTick: normalizeSource(assignments.warningTick, 'warningTick'),
      finished: normalizeSource(assignments.finished, 'finished'),
    },
  }
}
