/**
 * Shared timer-domain data-transfer types.
 *
 * These are the shapes that cross the client/server boundary: the browser repository, the
 * `/api/workouts` and `/api/sessions` route handlers, and the Prisma rows all describe the
 * same records. Timestamps are epoch milliseconds so a DTO survives `JSON.stringify` and
 * `structuredClone` (IndexedDB) unchanged — the API layer converts to and from `Date` when
 * it talks to Prisma.
 *
 * This module used to hold expenses boilerplate from the project template. It now exports
 * timer-domain types and nothing else (requirements 13.1, 13.2).
 *
 * Requirements: 6.5, 8.8, 13.1
 */

/** A workout family. Kept in lockstep with the `WorkoutType` enum in `prisma/schema.prisma`. */
export type WorkoutType = 'BOXING' | 'MMA' | 'CUSTOM'

/**
 * A reusable workout definition.
 *
 * `id` is generated by the client so the same record can be written to browser storage and
 * upserted server-side under one identity (requirement 8.5).
 */
export interface WorkoutDTO {
  id: string
  name: string
  type: WorkoutType
  rounds: number
  roundSeconds: number
  restSeconds: number
  prepSeconds: number
  /** Epoch milliseconds. */
  createdAt: number
}

/**
 * One recorded run of a workout — a history row.
 *
 * `workoutName` and `type` are snapshots taken at recording time and stored on the session
 * itself, so history stays readable after the workout definition is deleted
 * (requirements 6.4, 6.6).
 */
export interface WorkoutSessionDTO {
  id: string
  /** The workout definition this run came from, when it is known. */
  workoutId?: string | null
  workoutName: string
  type: WorkoutType
  roundsPlanned: number
  /** In `[0, roundsPlanned]`. */
  roundsCompleted: number
  /** Effective elapsed milliseconds, excluding time spent paused; >= 0. */
  totalDurationMs: number
  /** `true` only when the run reached phase `finished`. */
  completed: boolean
  /** Epoch milliseconds. */
  startedAt: number
  /** Epoch milliseconds. */
  endedAt: number
}
